[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'
hook_add = '''
  source ~/.config/nvim/plugins/vim-autoclose.vim
'''


[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.config/nvim/plugins/vim-quickrun.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/nvim/plugins/anzu.vim
'''

[[plugins]]
repo  = 'cespare/vim-toml'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo ='vim-airline/vim-airline' 

[[plugins]]
repo = 'tpope/vim-commentary'


[[plugins]]
repo = 'jonathanfilip/vim-lucius' 
hook_add = '''
  source ~/.config/nvim/plugins/vim-lucius.vim
'''
[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = '''
  source ~/.config/nvim/plugins/seiya.rc.vim
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  source ~/.config/nvim/plugins/winresizer.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''  
  let g:openbrowser_browser_commands = [ {'name': 'google-chrome-stable',  'args': ['{browser}', '{uri}']} ]
'''


[[plugins]]
repo = 'tomasr/molokai' 
hook_add = '''
  source ~/.config/nvim/plugins/molokai.vim
'''
