[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']
hook_add = '''
  source ~/.config/nvim/plugins/neoinclude.vim
'''


[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install & npm install"'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','eruby','php', 'javascript', 'javascriptreact', 'vue']
hook_add = '''
  source ~/.config/nvim/plugins/emmet-vim.vim
'''

#[[plugins]]
#repo = 'vim-scripts/vim-auto-save'
#on_ft = ['html']
#hook_add = '''
#  source ~/.config/nvim/plugins/vim-auto-save.vim
#'''

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']
hook_add = '''
'''


[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'alampros/vim-styled-jsx'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
  source ~/.config/nvim/plugins/vim-vue.vim
'''

[[plugins]]
repo = 'w0rp/ale.git'
on_source = ['lightline.vim']
hook_add = '''
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '']
  let g:ale_echo_msg_format = '[%linter%] %s'
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']


[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
hook_add = '''
  source ~/.config/nvim/plugins/vim-flutter.vim
'''
