[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']
hook_add = '''
  source ~/.config/nvim/plugins/neoinclude.vim
'''



[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete-jedi.vim
'''

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','eruby','php']
hook_add = '''
  source ~/.config/nvim/plugins/emmet-vim.vim
'''

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
on_ft = ['html']
hook_add = '''
  source ~/.config/nvim/plugins/vim-auto-save.vim
'''

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']
hook_add = '''
'''
