[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']
hook_add = '''
  source ~/.config/nvim/plugins/neoinclude.vim
'''



[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete-jedi.vim
'''
